(deftheme aurora "My Custom Theme")

(let ((bg         "#191724")
      (bg-soft    "#1E1E2E")
      (bg-hl      "#575268")
      (fg         "#D9E0EE")
      (cursor     "#F5E0DC")
      (black      "#6E6C7E")
      (red        "#F28FAD")
      (green      "#ABE9B3")
      (yellow     "#FAE3B0")
      (blue       "#96CDFB")
      (magenta    "#F5C2E7")
      (cyan       "#89DCEB")
      (white      "#D9E0EE")
      (comment    "#6A9955")
      (variable   "#9CDCFE")
      (type       "#4EC9B0")
      (constant   "#4FC1FF")
      (builtin    "#569CD6")
      (number     "#B5CEA8")
      (string     "#CE9178")
      (escape     "#D7BA7D")
      (func       "#DCDCAA")
      (keyword    "#569CD6")
      (control    "#C586C0")
      (operator   "#D4D4D4"))

  (custom-theme-set-faces
   'aurora

   `(default                        ((t :background ,bg :foreground ,fg)))
   `(cursor                         ((t :background ,cursor)))
   `(fringe                         ((t :background ,bg :foreground ,black)))
   `(region                         ((t :background ,bg-hl)))
   `(highlight                      ((t :background ,bg-hl)))
   `(secondary-selection            ((t :background ,bg-soft)))
   `(hl-line                        ((t :background ,bg-soft)))
   `(match                          ((t :background ,bg-hl :foreground ,white)))
   `(shadow                         ((t :foreground ,black)))
   `(trailing-whitespace            ((t :background ,red)))
   `(vertical-border                ((t :foreground ,bg-hl)))
   `(window-divider                 ((t :foreground ,bg-hl)))
   `(minibuffer-prompt              ((t :foreground ,blue :weight bold)))
   `(error                          ((t :foreground ,red)))
   `(warning                        ((t :foreground ,yellow)))
   `(success                        ((t :foreground ,green)))

   `(line-number                    ((t :background ,bg :foreground ,black)))
   `(line-number-current-line       ((t :background ,bg :foreground ,fg :weight bold)))

   `(isearch                        ((t :background ,yellow :foreground ,bg)))
   `(isearch-fail                   ((t :background ,red :foreground ,bg)))
   `(lazy-highlight                 ((t :background ,bg-hl :foreground ,fg)))

   `(font-lock-comment-face         ((t :foreground ,comment :slant italic)))
   `(font-lock-comment-delimiter-face ((t :foreground ,comment :slant italic)))
   `(font-lock-doc-face             ((t :foreground ,comment :slant italic)))
   `(font-lock-string-face          ((t :foreground ,string)))
   `(font-lock-regexp-grouping-construct ((t :foreground ,escape)))
   `(font-lock-escape-face          ((t :foreground ,escape)))
   `(font-lock-constant-face        ((t :foreground ,constant)))
   `(font-lock-number-face          ((t :foreground ,number)))
   `(font-lock-builtin-face         ((t :foreground ,builtin)))
   `(font-lock-keyword-face         ((t :foreground ,keyword)))
   `(font-lock-type-face            ((t :foreground ,type)))
   `(font-lock-function-name-face   ((t :foreground ,func)))
   `(font-lock-variable-name-face   ((t :foreground ,variable)))
   `(font-lock-preprocessor-face    ((t :foreground ,control)))
   `(font-lock-negation-char-face   ((t :foreground ,red)))
   `(font-lock-operator-face        ((t :foreground ,operator)))
   `(font-lock-punctuation-face     ((t :foreground ,operator)))
   `(font-lock-warning-face         ((t :foreground ,yellow :weight bold)))

   `(mode-line                      ((t :background ,bg-hl :foreground ,fg)))
   `(mode-line-inactive             ((t :background ,bg-soft :foreground ,black)))
   `(mode-line-highlight            ((t :background ,magenta :foreground ,bg)))
   `(mode-line-buffer-id            ((t :foreground ,magenta :weight bold)))

   `(completions-common-part        ((t :foreground ,blue)))
   `(completions-first-difference   ((t :foreground ,magenta :weight bold)))
   `(vertico-current                ((t :background ,bg-hl)))

   `(corfu-default                  ((t :background ,bg-soft)))
   `(corfu-current                  ((t :background ,bg-hl :foreground ,white)))
   `(corfu-border                   ((t :background ,bg-hl)))
   `(corfu-annotations              ((t :foreground ,black)))

   `(which-key-key-face             ((t :foreground ,blue :weight bold)))
   `(which-key-separator-face       ((t :foreground ,black)))
   `(which-key-description-face     ((t :foreground ,fg)))
   `(which-key-group-description-face ((t :foreground ,magenta :weight bold)))
   `(which-key-command-description-face ((t :foreground ,cyan)))

   `(org-level-1                    ((t :foreground ,magenta :weight bold :height 1.3)))
   `(org-level-2                    ((t :foreground ,blue    :weight bold :height 1.2)))
   `(org-level-3                    ((t :foreground ,cyan    :weight bold :height 1.1)))
   `(org-level-4                    ((t :foreground ,green   :weight bold)))
   `(org-level-5                    ((t :foreground ,yellow  :weight bold)))
   `(org-link                       ((t :foreground ,blue :underline t)))
   `(org-code                       ((t :foreground ,string :background ,bg-soft)))
   `(org-verbatim                   ((t :foreground ,constant :background ,bg-soft)))
   `(org-block                      ((t :background ,bg-soft)))
   `(org-block-begin-line           ((t :foreground ,black :background ,bg-soft)))
   `(org-block-end-line             ((t :foreground ,black :background ,bg-soft)))
   `(org-date                       ((t :foreground ,cyan :underline t)))
   `(org-todo                       ((t :foreground ,red :weight bold)))
   `(org-done                       ((t :foreground ,green :weight bold)))
   `(org-tag                        ((t :foreground ,black)))
   `(org-drawer                     ((t :foreground ,black)))
   `(org-special-keyword            ((t :foreground ,builtin)))

   `(flymake-error                  ((t :underline (:style wave :color ,red))))
   `(flymake-warning                ((t :underline (:style wave :color ,yellow))))
   `(flymake-note                   ((t :underline (:style wave :color ,blue))))

   `(eglot-highlight-symbol-face    ((t :background ,bg-hl)))
   `(eglot-inlay-hint-face          ((t :foreground ,black :slant italic)))

   `(diff-added                     ((t :background "#1e3a2f" :foreground ,green)))
   `(diff-removed                   ((t :background "#3a1e2a" :foreground ,red)))
   `(diff-header                    ((t :background ,bg-soft)))

   `(magit-section-heading          ((t :foreground ,yellow :weight bold)))
   `(magit-section-highlight        ((t :background ,bg-soft)))
   `(magit-diff-added               ((t :background "#1e3a2f" :foreground ,green)))
   `(magit-diff-removed             ((t :background "#3a1e2a" :foreground ,red)))
   `(magit-diff-added-highlight     ((t :background "#254d3c" :foreground ,green)))
   `(magit-diff-removed-highlight   ((t :background "#4d2535" :foreground ,red)))
   `(magit-branch-local             ((t :foreground ,blue)))
   `(magit-branch-remote            ((t :foreground ,green)))
   `(magit-hash                     ((t :foreground ,black)))
   `(magit-tag                      ((t :foreground ,yellow)))

   `(internal-border                ((t :background ,bg-soft)))))

(provide-theme 'aurora)
